# Generated by Django 4.1 on 2022-08-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generate_timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('client_name', models.CharField(max_length=20)),
                ('project_manager', models.CharField(max_length=20)),
                ('month', models.PositiveIntegerField(default=1, max_length=2)),
                ('year', models.PositiveIntegerField(default=2022, max_length=4)),
                ('leave_taken', models.DateField(default='2022-01-01')),
                ('holidays', models.DateField(default='2022-01-01')),
                ('extra_work', models.DateField(default='2022-01-01')),
            ],
        ),
    ]
