# Generated by Django 4.1 on 2022-08-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generate_timesheet',
            name='month',
        ),
        migrations.RemoveField(
            model_name='generate_timesheet',
            name='year',
        ),
        migrations.AddField(
            model_name='generate_timesheet',
            name='month_data',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='generate_timesheet',
            name='year_data',
            field=models.PositiveIntegerField(default=2022),
        ),
    ]
