# Generated by Django 4.1 on 2022-08-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_generate_timesheet_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_timesheet',
            name='extra_work',
            field=models.DateField(blank=True, default='2022-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='generate_timesheet',
            name='holidays',
            field=models.DateField(blank=True, default='2022-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='generate_timesheet',
            name='leave_taken',
            field=models.DateField(blank=True, default='2022-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='generate_timesheet',
            name='month_data',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='generate_timesheet',
            name='year_data',
            field=models.PositiveIntegerField(blank=True, default=2022, null=True),
        ),
    ]
